### PR TITLE
Fix driver compilation under linux >= 4.6

### PR DESCRIPTION
**Pull request by marzoul**

### CODE REVIEW

**Comment by drichmond** [comment]
Cool, thanks! I'll get to checking this out soon.

**Comment by marzoul** [comment]
I couldn't find how to change where to merge the previous pull request, so I created another one...
But v2.2.2 is still in development so having it merged also in master (= v2.2.1) would still be useful as support for recent systems. Not mandatory, just a suggestion :-)

**Comment by drichmond** [comment]
My plan is to have 2.2.2 out in the next couple of weeks, so it's a moot
point. There's more than one important bug fix in it.

**Comment by drichmond** [comment]
Can you confirm that the merge worked correctly by running the testutil.sh script on one of the example chnl_tester designs? I can't get a 4.6 kernel to install.

**Pull request merged**
