### PR TITLE
Fix driver compilation under linux >= 4.6

### PR DESCRIPTION
**Pull request by marzoul**
The Linux API for functions get_user_pages() and page_cache_release() has changed since Linux 4.6.
The proposed fix adds preprocessor conditions to enable the right function call.

More information (and inspiration) from:
https://patchwork.kernel.org/patch/8441921/
https://devtalk.nvidia.com/default/topic/926824/linux/364-1-2-5-won-t-compile-against-latest-kernel-git-tree-patches-for-4-6-0-rc3-included-/2

The proposed fix was tested successfully under a Dell Precision T3500 workstation running ArchLinux x64 with kernel Linux 4.6.4.

### CODE REVIEW

**Comment by drichmond** [comment]
Awesome! I'll test it too. 

Can you retarget your pull request into the RIFFA 2.2.2 development branch?

**Comment by marzoul** [comment]
Indeed. Done!

**Comment by marzoul** [comment]
... or maybe you wanted a pull request on the devel/2.2.2 branch?

**Comment by drichmond** [comment]
To deve/RIFFA/2.2.2 branch, if you could.

Dustin

**Pull request closed without merging**
